/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 developer.glb -T 
Files: developer.glb [981.62KB] > /Users/hsuwinlat/Desktop/jsm pj/threejscc-portfolio/public/models/developer-transformed.glb [395.08KB] (60%)
*/

import React, { useEffect, useRef } from 'react';
import { useGraph } from '@react-three/fiber';
import { useAnimations, useFBX, useGLTF } from '@react-three/drei';
import { SkeletonUtils } from 'three-stdlib';
import * as THREE from 'three';

const Developer = ({ animationName = 'idle', ...props }) => {
  const group = useRef();

  const { scene } = useGLTF('/models/animations/developer.glb');
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene]);
  const { nodes, materials } = useGraph(clone);

  // Change appearance to match user
  React.useEffect(() => {
    // Create the skin color once
    const skinColor = new THREE.Color('#3b2219'); // Dark brown skin tone

    // Apply consistent skin tone to all body parts
    Object.keys(materials).forEach((key) => {
      // Apply skin color to all materials containing "Skin" or "Body"
      if (key.includes('Skin') || key === 'Wolf3D_Body') {
        materials[key].color = skinColor;
        // Enhance skin properties for better light reflection
        materials[key].roughness = 0.7; // Less shiny skin
        materials[key].metalness = 0.1; // Slight sheen
        materials[key].envMapIntensity = 1.2; // Better environmental reflection
      }
    });

    // Now apply specific colors to other materials
    if (materials.Wolf3D_Hair) {
      materials.Wolf3D_Hair.color = new THREE.Color('#0a0a0a'); // Black hair
    }

    if (materials.Wolf3D_Outfit_Top) {
      materials.Wolf3D_Outfit_Top.color = new THREE.Color('#2e3a65'); // Dark blue shirt like in your photo
    }

    if (materials.Wolf3D_Outfit_Bottom) {
      materials.Wolf3D_Outfit_Bottom.color = new THREE.Color('#242424'); // Dark gray pants
    }

    if (materials.Wolf3D_Outfit_Footwear) {
      materials.Wolf3D_Outfit_Footwear.color = new THREE.Color('#ffffff'); // White shoes
    }

    if (materials.Wolf3D_Teeth) {
      materials.Wolf3D_Teeth.color = new THREE.Color('#ffffff'); // White teeth for your smile
    }

    if (materials.Wolf3D_Glasses) {
      materials.Wolf3D_Glasses.color = new THREE.Color('#2a2a2a'); // Dark glasses frames
      if (materials.Wolf3D_Glasses.metalness) {
        materials.Wolf3D_Glasses.metalness = 0.5; // Make glasses less shiny
      }
    }
  }, [materials]);

  const { animations: idleAnimation } = useFBX('/models/animations/idle.fbx');
  const { animations: saluteAnimation } = useFBX('/models/animations/salute.fbx');
  const { animations: clappingAnimation } = useFBX('/models/animations/clapping.fbx');
  const { animations: victoryAnimation } = useFBX('/models/animations/victory.fbx');

  // Uncomment these lines after adding the FBX files
  // const { animations: waveAnimation } = useFBX('/models/animations/wave.fbx');
  // const { animations: danceAnimation } = useFBX('/models/animations/dance.fbx');

  idleAnimation[0].name = 'idle';
  saluteAnimation[0].name = 'salute';
  clappingAnimation[0].name = 'clapping';
  victoryAnimation[0].name = 'victory';

  // Uncomment these lines after adding the FBX files
  // waveAnimation[0].name = 'wave';
  // danceAnimation[0].name = 'dance';

  const { actions } = useAnimations(
    [
      idleAnimation[0],
      saluteAnimation[0],
      clappingAnimation[0],
      victoryAnimation[0],
      // Uncomment these lines after adding the FBX files
      // waveAnimation[0],
      // danceAnimation[0]
    ],
    group,
  );

  useEffect(() => {
    actions[animationName].reset().fadeIn(0.5).play();
    return () => actions[animationName].fadeOut(0.5);
  }, [animationName]);

  return (
    <group ref={group} {...props} dispose={null}>
      <primitive object={nodes.Hips} />
      <skinnedMesh
        geometry={nodes.Wolf3D_Hair.geometry}
        material={materials.Wolf3D_Hair}
        skeleton={nodes.Wolf3D_Hair.skeleton}
      />
      <skinnedMesh
        geometry={nodes.Wolf3D_Glasses.geometry}
        material={materials.Wolf3D_Glasses}
        skeleton={nodes.Wolf3D_Glasses.skeleton}
      />
      <skinnedMesh
        geometry={nodes.Wolf3D_Body.geometry}
        material={materials.Wolf3D_Body}
        skeleton={nodes.Wolf3D_Body.skeleton}
      />
      <skinnedMesh
        geometry={nodes.Wolf3D_Outfit_Bottom.geometry}
        material={materials.Wolf3D_Outfit_Bottom}
        skeleton={nodes.Wolf3D_Outfit_Bottom.skeleton}
      />
      <skinnedMesh
        geometry={nodes.Wolf3D_Outfit_Footwear.geometry}
        material={materials.Wolf3D_Outfit_Footwear}
        skeleton={nodes.Wolf3D_Outfit_Footwear.skeleton}
      />
      <skinnedMesh
        geometry={nodes.Wolf3D_Outfit_Top.geometry}
        material={materials.Wolf3D_Outfit_Top}
        skeleton={nodes.Wolf3D_Outfit_Top.skeleton}
      />
      <skinnedMesh
        name="EyeLeft"
        geometry={nodes.EyeLeft.geometry}
        material={materials.Wolf3D_Eye}
        skeleton={nodes.EyeLeft.skeleton}
        morphTargetDictionary={nodes.EyeLeft.morphTargetDictionary}
        morphTargetInfluences={nodes.EyeLeft.morphTargetInfluences}
      />
      <skinnedMesh
        name="EyeRight"
        geometry={nodes.EyeRight.geometry}
        material={materials.Wolf3D_Eye}
        skeleton={nodes.EyeRight.skeleton}
        morphTargetDictionary={nodes.EyeRight.morphTargetDictionary}
        morphTargetInfluences={nodes.EyeRight.morphTargetInfluences}
      />
      <skinnedMesh
        name="Wolf3D_Head"
        geometry={nodes.Wolf3D_Head.geometry}
        material={materials.Wolf3D_Skin}
        skeleton={nodes.Wolf3D_Head.skeleton}
        morphTargetDictionary={nodes.Wolf3D_Head.morphTargetDictionary}
        morphTargetInfluences={nodes.Wolf3D_Head.morphTargetInfluences}
      />
      <skinnedMesh
        name="Wolf3D_Teeth"
        geometry={nodes.Wolf3D_Teeth.geometry}
        material={materials.Wolf3D_Teeth}
        skeleton={nodes.Wolf3D_Teeth.skeleton}
        morphTargetDictionary={nodes.Wolf3D_Teeth.morphTargetDictionary}
        morphTargetInfluences={nodes.Wolf3D_Teeth.morphTargetInfluences}
      />
    </group>
  );
};

useGLTF.preload('/models/animations/developer.glb');

export default Developer;